name: Scheduled check

# Controls when the action will run.
on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.status || github.token }}
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
